### ISSUE TITLE
[BUG] Hot reload on 0.0.10

### ISSUE THREAD

**Issue by AndariasSilvanus** [airyrooms/maleo.js#130]
**Describe the bug**
Hot reload doesn't produce new changes but instead produce 'error'

**To Reproduce**
1. Start `yarn dev`
2. Modify your file and save it
3. Return back to your browser

**Expected behavior**
Expectation: the browser will display new changes

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac OSX High Sierra]

**Additional context**

**Comment by alvinkl** [comment]
HOT issue showing `error` also fixed on PR #133
this caused due to false route matching and async action wasn't awaited, so it returns empty array.
