### ISSUE TITLE
[FEATURE] Add html doctype

### ISSUE THREAD

**Issue by rakasiwi23** [airyrooms/maleo.js#173]
**Is your feature request related to a problem? Please describe.**
Need to add html doctype as best practice for html markup (every site must have it !)

**Describe the solution you'd like**
I thought it's simple to just add ```<!DOCTYPE html>``` on top
```
<!DOCTYPE html> <!-- add doctype here -->
<html lang="en">
  <Header />

    <body>
      <Main />

    <Scripts />
  </body>
</html>
```
but the problem is that you guys create the markup not from ```.html``` file. And make it difficult or even impossible to add ```<!DOCTYPE html>``` there ```.tsx```

**Comment by alvinkl** [comment]
Nice finding @rakasiwi23! Would you like to fix the issue? I think it is fairly simple for first issue :)

**Comment by rakasiwi23** [comment]
I don't think this is a simple first issue 🤔, you need to change bundle/compiler flow. From ```.tsx``` file attach the builded script to ```.html``` file and then send it to client side via server side???

**Comment by alvinkl** [comment]
I was thinking to just prepend 
`<!DOCTYPE html>` tag during server side render. we use `react.renderToString` method, which translates the react component into string during SSR.
Ok it may not be that simple, but still bearable, would you like to try? I would be happy to guide you out, if you have any questions
