### ISSUE TITLE
[BUG] getInitialProps doesn't work on child component

### ISSUE THREAD

**Issue by rakasiwi23** [airyrooms/maleo.js#187]
**Describe the bug**
`getInitialProps` doesn't work on children component, it only work on RootComponent

**To Reproduce**
I have this `RootComponent.jsx`:
```
import React from 'react'

import ChildComponent from './components'

const RootComponent = props => {
  return (
    <h1>
      Hello this is {props.test} <ChildComponent />
    </h1>
  )
}

RootComponent.getInitialProps = ctx => {
  return { test: 'this is works' }
}

export default RootComponent
```
and this `ChildComponent` which I put under folder `components/index.jsx`:
```
import React from 'react'

const ChildComponent = props => {
  console.log(props)
  return <p>Child Component</p>
}

ChildComponent.getInitialProps = ctx => {
  console.log('this from child component', ctx)

  return { test: 'this is not works :(' }
}

export default ChildComponent
```

The `console.log(props)` at `ChildComponent` just return `{}` an empty object. And `console.log('this from child component', ctx)` give no result (nothing appear on my terminal).

as for the code from `RootComponent.jsx` run without problem (`getInitialProps` is work)

**Expected behavior**
What I expect is that `getInitialProps` can be use on any component, am I wrong?

**Additional**
I'm using `"@airy/maleo": "^0.2.1"` version

**Comment by alvinkl** [comment]
Hi @rakasiwi23, thank you for opening up the discussion regarding this matter.
But I think this is not an issue, as this is expected to happen, `getInitialProps` API is only exposed for the page components that are registered on `routes.json`.

**Comment by rakasiwi23** [comment]
Ok, got it. Thanks 👍
will close this issue
