### ISSUE TITLE
[FEATURE] Authentication Handler

### ISSUE THREAD

**Issue by vanniaferdina** [airyrooms/maleo.js#189]
I need authentication feature on the framework, e.g. additional function that receive boolean (authorised/not) and redirection path.

**Comment by alvinkl** [comment]
We have added new function on `@airy/maleo/utils` named `getMatchedRoutes` to return all matching routes including all the properties you passed on `routes.json` file.
And also we have set `getInitialProps` to block render until all the `getInitialProps` has been called, you can add authentication logic there.

I think those 2 things already satisfy your need, I'm going to close this issue.
For further questions please continue on our discord channel. Thank you
