### ISSUE TITLE
[BUG] Handling client object on server side render `window`, `global` & `document` is not defined

### ISSUE THREAD

**Issue by rakasiwi23** [airyrooms/maleo.js#190]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac OSX High Sierra]

**Additional context**

**Comment by alvinkl** [comment]
I think we shouldn't handle this case, since it is expected to have undefined `window` and `document` value on server as they are browser objects.
I'm closing this issue.
Thank you!
