### ISSUE TITLE
[FEATURE] Custom config for CSP(Content Security Policy) via helmet

### ISSUE THREAD

**Issue by rakasiwi23** [airyrooms/maleo.js#208]
Need to customize CSP via helmet for whitelisting <script> from other domain, ex: apis.google.com

**Comment by alvinkl** [comment]
Hi @rakasiwi23 thank you for the feature request, I think it make sense to give user ability to customise CSP. I have added the feature and already merged the PR. Please kindly refer to our latest readme at `canary`. Thank you
