### ISSUE TITLE
[FEATURE] Add matched routes on Wrap GetInitialProps

### ISSUE THREAD

**Issue by AndariasSilvanus** [airyrooms/maleo.js#219]
**Is your feature request related to a problem? Please describe.**
I want to get matched routes on Wrap GetInitialProps

**Describe the solution you'd like**
Server & Client pass matched routes on Wrap GetInitialProps as an argument

**Describe alternatives you've considered**

**Additional context**

**Comment by alvinkl** [comment]
I think it will be nice to have that feature as well!

It would be nice too if we can have the attributes that are being passed to `routes.json` so user will have better customisability and usage for the routes file.
